AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KWAK

  Tests for candidates and HR

Globals:
  Function:
    Timeout: 20

Resources:
  TestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tests
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  GetTestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.GetTests::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            Path: /tests
            Method: get
  AddTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.AddTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            Path: /tests
            Method: post
  UpdateTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.UpdateTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            Path: /test/{id}
            Method: put

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
