AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KWAK

  Tests for candidates and HR

Globals:
  Function:
    Timeout: 20

Resources:
  KwakApi:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False
        DefaultAuthorizer: AWS_IAM
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      StageName: dev

  TestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tests
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CandidatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CandidateTests
      AttributeDefinitions:
        - AttributeName: CandidateId
          AttributeType: S
        - AttributeName: TestId
          AttributeType: S
      KeySchema:
        - AttributeName: CandidateId
          KeyType: HASH
        - AttributeName: TestId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  GetTestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.GetTests::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /tests
            Method: get
  AddTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.AddTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /tests
            Method: post
  UpdateTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.UpdateTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /tests/{id}
            Method: put
  DeleteTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AmazonDynamoDBFullAccess
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.tests.DeleteTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /tests/{id}
            Method: delete
  GetCandidatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - Statement:
          - Sid: AllowCognito
            Effect: "Allow"
            Action: [
              "cognito-idp:*"
            ]
            Resource: '*'
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.candidates.GetCandidates::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /candidates
            Method: get
  AddCandidateTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
          - Sid: AllowCognito
            Effect: "Allow"
            Action: [
              "cognito-idp:*"
            ]
            Resource: '*'
      CodeUri: RecruitmentAPI
      Handler: recruitmentapi.endpoints.candidates.tests.AddCandidateTest::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        GetTests:
          Type: Api
          Properties:
            RestApiId: !Ref KwakApi
            Path: /candidates/{candidateId}/tests
            Method: post

Outputs:
  Api:
    Description: "API Gateway endpoint URL for KWAK"
    Value: !Sub "https://${KwakApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
